notifications:
  email: false

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
           PLAT=manylinux2010_x86_64

install:
  - docker pull $DOCKER_IMAGE

script:
  - sudo chmod +x ./build-wheels.sh
  - docker run --rm -e PLAT=$PLAT -v `pwd`:/ptb $DOCKER_IMAGE $PRE_CMD /ptb/build-wheels.sh
  - ls wheelhouse/

deploy:
  provider: releases
  api_key:
    secure: "qnEbN/dJwMarCXnw88oOUjQCNAIca6JGx0ndAxUhfbTN4UyQlEijLEH8pH7jzSJMrhx8zhviwoHfF+TChZkpfHwxcvgkGbEDRlEibbnW1mRUXADB2sAXtKVA5YGQGLOKh23TF5je8Rw7HlWx+MX5Za0I2HIePus9xBEEpyUQEC41XoqP6mTgENKEhy/FTKHCv9hPf4vVMZvY1F7ndzUPx5FqdIOQEnpDgyPpFkt2rWq3ZyWVU/+stNHMt8rlVURt7IgomHVLcoIA0IhLm5ugmJ4VhdhMw3MMvMGv5XpT011beOB0VKVVAP81k5QGTmgerrQK5hv3gQb3v6twPuSatRmccQ2HvIlvWHpyVcGMh/jDW2zDhrRuYMIy0a/7Lx9xNBxFeoen7Av8JLNuFOB40X0Dizysk4WXJpN8TSOQ6fhJ1+X1YV981rewVOrAwOFT9o0pPfHFBpz9vpH1ciS5gZzdqBz27n9A+cmTX/NwO0n11lEpgFN7e/NoWnnnAd1rVFXwj4YYalviUHBi4QMGGyno31I66UaqKBqhQAva7etNX5+NZmlWQ/YYZwnhhcmv+BwTlji96cCJFq0DcqkDw0PwqI37rQyyZlB+ekOGzTRbMP1aVMUSyUkkY2RveWLh0+kboEWCLOX2CoRXnTiuPEsYlJw8Au5bgfaPgtnV0f4="
  file: 
    - 'wheelhouse/psychtoolbox-3.0.16-cp27-cp27m-manylinux2010_x86_64.whl'
    - 'wheelhouse/psychtoolbox-3.0.16-cp36-cp36m-manylinux2010_x86_64.whl'
    - 'wheelhouse/psychtoolbox-3.0.16-cp37-cp37m-manylinux2010_x86_64.whl'
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
