notifications:
  email: false

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
           PLAT=manylinux2010_x86_64

install:
  - docker pull $DOCKER_IMAGE

script:
  - sudo chmod +x ./build-wheels.sh
  - docker run --rm -e PLAT=$PLAT -v `pwd`:/ptb $DOCKER_IMAGE $PRE_CMD /ptb/build-wheels.sh
  - ls wheelhouse/
