notifications:
  email: false

language: python

env:
  global:
      # only 64-bit
      - CIBW_SKIP="cp34-* cp35-* *-win32 *-manylinux_i686"
      - CIBW_BUILD=cp3?-*
      - CIBW_MANYLINUX_X86_64_IMAGE=manylinux2010 # switch to 2014 eventually
      - CIBW_BEFORE_BUILD="python -m pip install numpy"
      - CIBW_BEFORE_BUILD_LINUX="bash ./prebuild_linux.sh && python -m pip install numpy"
      - CIBW_TEST_COMMAND="python -c \"import os;import pkgutil;x=pkgutil.get_loader('psychtoolbox');
for root, dirs, files in os.walk(os.path.dirname(x.path)):
    for filename in files: print(filename)\" && python -c \"import psychtoolbox as ptb; print(ptb.GetSecs())\""

matrix:
  include:
    # perform a linux build
    - services: docker
    # and a mac build
    - os: osx
      language: generic
    # and a windows build
    - os: windows
      language: generic
      before_install:
        - choco install python --version 3.8.0
        - export PATH="/c/Python38:/c/Python/Scripts:$PATH"

install:
  - python -m pip install cibuildwheel==1.1.0
  - if [ "${TRAVIS_OS_NAME:-}" == "linux" ]; then
    cp prebuild_linux.sh psychtoolbox-3/prebuild_linux.sh;
    fi

script:
  # build the wheels, put them into './wheelhouse'
  - cd psychtoolbox-3 && python -m cibuildwheel --output-dir ../wheelhouse && cd ..

deploy:
  provider: releases
  api_key:
    secure: "qnEbN/dJwMarCXnw88oOUjQCNAIca6JGx0ndAxUhfbTN4UyQlEijLEH8pH7jzSJMrhx8zhviwoHfF+TChZkpfHwxcvgkGbEDRlEibbnW1mRUXADB2sAXtKVA5YGQGLOKh23TF5je8Rw7HlWx+MX5Za0I2HIePus9xBEEpyUQEC41XoqP6mTgENKEhy/FTKHCv9hPf4vVMZvY1F7ndzUPx5FqdIOQEnpDgyPpFkt2rWq3ZyWVU/+stNHMt8rlVURt7IgomHVLcoIA0IhLm5ugmJ4VhdhMw3MMvMGv5XpT011beOB0VKVVAP81k5QGTmgerrQK5hv3gQb3v6twPuSatRmccQ2HvIlvWHpyVcGMh/jDW2zDhrRuYMIy0a/7Lx9xNBxFeoen7Av8JLNuFOB40X0Dizysk4WXJpN8TSOQ6fhJ1+X1YV981rewVOrAwOFT9o0pPfHFBpz9vpH1ciS5gZzdqBz27n9A+cmTX/NwO0n11lEpgFN7e/NoWnnnAd1rVFXwj4YYalviUHBi4QMGGyno31I66UaqKBqhQAva7etNX5+NZmlWQ/YYZwnhhcmv+BwTlji96cCJFq0DcqkDw0PwqI37rQyyZlB+ekOGzTRbMP1aVMUSyUkkY2RveWLh0+kboEWCLOX2CoRXnTiuPEsYlJw8Au5bgfaPgtnV0f4="
  file_glob: true
  file: 
    - 'wheelhouse/psychtoolbox*.whl'
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
