environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

  matrix:
    - PYTHON: C:\Python37-x64
      PYTHON_VERSION: 3.7
      PYTHON_ARCH: 64

    - PYTHON: C:\Python36-x64
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 64

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  - "ECHO \"%APPVEYOR_SCHEDULED_BUILD%\""
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
          throw "There are newer queued builds for this pull request, failing early." }

cache:
  # Cache downloaded pip packages and built wheels.
  - '%LOCALAPPDATA%\pip\Cache\http'

install:
  - C:\cygwin\bin\du -hs "%LOCALAPPDATA%\pip\Cache"
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

  # Check that we have the expected version and architecture for Python
  - python --version
  - >-
     %CMD_IN_ENV%
     python -c "import sys,platform,struct;
     print(sys.platform, platform.machine(), struct.calcsize('P') * 8, )"
  # Upgrade to the latest pip.
  - 'python -m pip install -U pip setuptools wheel'

  - "git submodule update --init --recursive"
  - "cd psychtoolbox-3"

  # build wheel
  - 'python -m pip wheel . -w wheels/'

  # install from wheel
  - 'python -m pip install psychtoolbox --no-index -f wheels'

build: off

test_script:
  # Run the tests appropriate for this entry in the test matrix. Skip tests
  # if we're just updating the cache.
  - 'python -c "import psychtoolbox as ptb; print(ptb.GetSecs())"'

artifacts:
  - path: psychtoolbox-3/wheels/psych*

deploy:
  description: 'Description'
  provider: GitHub
  auth_token:
    secure: "qnEbN/dJwMarCXnw88oOUjQCNAIca6JGx0ndAxUhfbTN4UyQlEijLEH8pH7jzSJMrhx8zhviwoHfF+TChZkpfHwxcvgkGbEDRlEibbnW1mRUXADB2sAXtKVA5YGQGLOKh23TF5je8Rw7HlWx+MX5Za0I2HIePus9xBEEpyUQEC41XoqP6mTgENKEhy/FTKHCv9hPf4vVMZvY1F7ndzUPx5FqdIOQEnpDgyPpFkt2rWq3ZyWVU/+stNHMt8rlVURt7IgomHVLcoIA0IhLm5ugmJ4VhdhMw3MMvMGv5XpT011beOB0VKVVAP81k5QGTmgerrQK5hv3gQb3v6twPuSatRmccQ2HvIlvWHpyVcGMh/jDW2zDhrRuYMIy0a/7Lx9xNBxFeoen7Av8JLNuFOB40X0Dizysk4WXJpN8TSOQ6fhJ1+X1YV981rewVOrAwOFT9o0pPfHFBpz9vpH1ciS5gZzdqBz27n9A+cmTX/NwO0n11lEpgFN7e/NoWnnnAd1rVFXwj4YYalviUHBi4QMGGyno31I66UaqKBqhQAva7etNX5+NZmlWQ/YYZwnhhcmv+BwTlji96cCJFq0DcqkDw0PwqI37rQyyZlB+ekOGzTRbMP1aVMUSyUkkY2RveWLh0+kboEWCLOX2CoRXnTiuPEsYlJw8Au5bgfaPgtnV0f4="
  artifact: 'psychtoolbox-3/wheels/psych*.whl'           # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
