environment:
  global:
      CIBW_SKIP: "cp34-* cp35-* *-win32"
      CIBW_BUILD: cp3?-*
      CIBW_BEFORE_BUILD: "python -m pip install numpy"
      CIBW_TEST_COMMAND: "python -c \"import psychtoolbox as ptb; print(ptb.GetSecs())\""
image:
  - Visual Studio 2015
build_script:
  # windows
  - cmd: git submodule -q update --init
  - cmd: pip install cibuildwheel==1.1.0
  - cmd: cd psychtoolbox-3 && cibuildwheel --output-dir ..\\wheelhouse && cd ..
artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels

deploy:
  description: 'Psychtoolbox Python wheels.'
  provider: GitHub
  auth_token:
    secure: KRnhI4rZvAFvrm5CvIJs7B8djoR6Y9/jJD+zOockN4XQH3w2bQZ0y0ERGA866K/J
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true        # deploy on tag push only